function B_d_slip = B_d_slip(obj,in2,in3,dt,in5)
%B_D_SLIP
%    B_D_SLIP = B_D_SLIP(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Nov-2023 23:07:28

length_base = in5(:,1);
u_lin1 = in3(1,:);
u_lin2 = in3(2,:);
wheel_slip = in5(:,2);
x_lin3 = in2(3,:);
t2 = cos(u_lin2);
t3 = cos(x_lin3);
t4 = sin(u_lin2);
t5 = sin(x_lin3);
t6 = 1.0./length_base;
t7 = wheel_slip-1.0;
B_d_slip = reshape([-dt.*t2.*t3.*t7,-dt.*t2.*t5.*t7,-dt.*t4.*t6.*t7,dt.*t3.*t4.*t7.*u_lin1,dt.*t4.*t5.*t7.*u_lin1,-dt.*t2.*t6.*t7.*u_lin1],[3,2]);
