function f_d_slip = f_d_slip(obj,in2,in3,dt,in5)
%F_D_SLIP
%    F_D_SLIP = F_D_SLIP(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Nov-2023 23:07:28

length_base = in5(:,1);
u_k1 = in3(1,:);
u_k2 = in3(2,:);
wheel_slip = in5(:,2);
x_k1 = in2(1,:);
x_k2 = in2(2,:);
x_k3 = in2(3,:);
t2 = cos(u_k2);
t3 = wheel_slip-1.0;
f_d_slip = [x_k1-dt.*t2.*t3.*u_k1.*cos(x_k3);x_k2-dt.*t2.*t3.*u_k1.*sin(x_k3);x_k3-(dt.*t3.*u_k1.*sin(u_k2))./length_base];
